### ISSUE TITLE
show in your website and other places that you support only <= cypress@12.5.1

### ISSUE THREAD

**Issue by chiptus** [currents-dev/currents-readme#2]
Thanks for the great product.

some places in the docs say that it's not supported since 13+ https://currents.dev/readme/integration-with-cypress/integrating-with-cypress#:~:text=We%20are%20suspending%20our%20support%20of%20Cypress%20test%20runner%20version%2013%2B

while in the same page, you say 12.6+ https://currents.dev/readme/integration-with-cypress/integrating-with-cypress#:~:text=(affected%20versions%20are%2012.6.0%2B).

The website says Currents supports every version (FAQ) - https://currents.dev/#faq:~:text=We%20support%20all,1%2D2%20weeks.

I think it should be stated. also, I think the docs should start with that. install command should be changed to `npm install cypress@12.5`

**Comment by agoldis** [comment]
@chiptus Good point! Thanks for paying attention, already updated the FAQ, will update the rest soon!

**Comment by agoldis** [comment]
@chiptus we have updated the documentation, thanks again for opening the issue!

_while in the same page, you say 12.6+ https://currents.dev/readme/integration-with-cypress/integrating-with-cypress#:~:text=(affected%20versions%20are%2012.6.0%2B)._

There were several attempts to block - the highlighted text refers to the switch from cy2 to cypress-cloud that  implements its own parallelization and recording protocol
